
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"
