
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: production          
      PORT: 10000                  
      MONGO_URI: ${MONGO_URI}       
      REDIS_URI: ${REDIS_URI}       
      JWT_SECRET: ${JWT_SECRET}    
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"
